version: "3.7"
services:
  flask:
    build: .
    command: gunicorn -w 1 -b 0.0.0.0:80 hello:app --reload
    environment:
        - FLASK_APP=hello.py
        - FLASK_DEBUG=1
        - PYTHONUNBUFFERED=True
    ports:
        - "80:80"
    volumes:
        - ./scripts:/scripts
